#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 480
#define WINDOW_HEIGHT 640
#define WINDOW_TITLE "DoodleSavik"
#define ENABLE_VSYNC true
#define SOUND_ON false

#define GRAVITY 13.81
#define GAME_SCALE 1.5

#define PLAYER_MAX_SPEED 400
#define PLAYER_ACCELERATION 2000
#define PLAYER_JUMP_FORCE -10
#define PLAYER_ON_JUMPER_FORCE -16

#define JUMPER_PROBALITY 13 //%
#define MOVABLE_BLOCK_VELOCITY_MIN 70
#define MOVABLE_BLOCK_VELOCITY_MAX 180

#endif // CONFIG_H
